config/routes.rb
Rails.application.routes.draw do
  resources :partners, only: %i[ index show ] do
    member do
      get :previous_events
    end
  end

  resources :events, only: %i[ index show ]

  get '/about' => 'home#about', as: :about

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#root"
end

app/models/partner.rb
class Partner < ApplicationRecord

  has_many :events

  has_many :partner_keywords, dependent: :destroy
  has_many :keywords, through: :partner_keywords

  belongs_to :address_ward, 
    foreign_key: :address_geo_enclosure_id,
    class_name: 'GeoEnclosure',
    optional: true

  scope :with_fuzzy_name, lambda { |name_string|
    name_string = name_string.to_s.gsub(/\s+/, '') # remove whitespace
    return none if name_string.blank?

    name_pattern = name_string
      .chars
      .map { |ch| sanitize_sql(ch) }
      .join('%')

    where('name LIKE ?', "%#{name_pattern}%")
  }

  scope :with_keyword, lambda { |keyword|
    return all if keyword.blank?

    joins(:partner_keywords)
      .where(partner_keywords: { keyword_id: keyword.id })
  }

  scope :with_slug, lambda { |slug_text|
    return none unless slug_text =~ /^(\d+)[\w\-]*$/

    where id: $1
  }

  scope :in_geo_enclosure, lambda { |geo_enclosure|
    return all if geo_enclosure.blank?

    return where(address_geo_enclosure_id: geo_enclosure.id) if geo_enclosure.ward_level?

    all # TODO is contained within ward set
  }

  def slug
    ([ id ] + name.downcase.split(/\W+/)).join('-')
  end

  class PartnerAddress
    attr_reader :street_address
    attr_reader :post_code
    attr_reader :ward

    def initialize(from)
      @street_address = from.address_street
      @post_code = from.address_postcode
      @ward = from.address_ward
    end

    def present?
      street_address.present? || post_code.present?
    end

    def to_s
      [ street_address, post_code ].keep_if(&:present?).join(', ')
    end
  end

  class PartnerContact
    attr_reader :email
    attr_reader :telephone

    def initialize(from)
      @email = from.contact_email
      @telephone = from.contact_telephone
    end

    def present?
      email.present? || telephone.present?
    end
  end

  def address
    @address ||= PartnerAddress.new(self)
  end

  def contact
    @contact ||= PartnerContact.new(self)
  end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  before_action :find_partner_for_param, only: %i[ show previous_events ]

  def index
    @partner_name_filter = params[:name].to_s.strip

    partner_keyword_param = params[:keyword].to_s.strip
    @keyword_for_filter = Keyword.where(name: partner_keyword_param).first if partner_keyword_param.present?

    geo_param = params[:geo]
    @geo_enclosure = GeoEnclosure.where(id: geo_param).first if geo_param.present?

    @partners = Partner.all

    # name
    @partners = @partners.with_fuzzy_name(@partner_name_filter) if @partner_name_filter.present?

    # keyword
    @partners = @partners.with_keyword(@keyword_for_filter) if @keyword_for_filter.present?

    # geo
    @partners = @partners.in_geo_enclosure(@geo_enclosure) if @geo_enclosure.present?
    
    @partners = @partners.order(:name)
  end

  def show
    @today = Time.now.beginning_of_day

    @upcoming_events = EventInstance
      .for_partner(@partner)
      .from_day_onward(@today)
      .order(:starts_at)

    @previous_events = EventInstance
      .for_partner(@partner)
      .before_date(@today)
  end

  def previous_events
    @today = Time.now.beginning_of_day
    @previous_event_instances = EventInstance
      .for_partner(@partner)
      .before_date(@today)
      .order(starts_at: :desc)
  end

  private

  def find_partner_for_param
    @partner = Partner.with_slug(params[:id]).first
    return if @partner.present?

    @message = "Could not find partner with that ID"
    render 'home/not_found', status: :not_found
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
  def partner_contact_info(partner)
    contact = partner.contact

    parts = []
    parts << link_to(contact.email, "mailto:#{contact.email}") if contact.email.present?
    parts << link_to(contact.telephone, "tel:#{contact.telephone}") if contact.telephone.present?

    parts.join(', ').html_safe
  end

  def partner_address_info(partner)
    parts = []
    parts << external_link_to(partner.url) if partner.url.present?
    parts << address_map_link_to(partner.address, :partners_path) if partner.address.present?

    parts.join(' | ').html_safe
  end

  def partner_index_filter_title_text(name_filter, keyword_filter, geo_filter)
    return if name_filter.blank? && keyword_filter.blank? && geo_filter.blank?

    text = [
      ("by title with '<em>#{name_filter}</em>'" if name_filter.present?),
      ("on keyword '<em>#{keyword_filter.name}</em>'" if keyword_filter.present?),
      ("in area <em>#{geo_filter.name}</em>" if geo_filter.present?)
    ].keep_if(&:present?).join(' and ')

    "Filtering #{text}".html_safe
  end

  def render_partner_event_by_day_list(event_instances)
    return if event_instances.empty?

    html = []
    last_day = event_instances.first.starts_at.beginning_of_day
    day_count = 1

    event_instances.each do |event_instance|
      day_of_event = event_instance.starts_at.beginning_of_day
      if day_of_event != last_day
        day_count += 1
        break if day_count > 7
        last_day = day_of_event

        html << "<h3>#{fancy_date_format(last_day)}</h3>"
      end

      time_part = fancy_time_format(event_instance.starts_at)
      event_name_part = link_to(event_instance.event.name, event_path(event_instance))

      html << "<p><span class='time'>#{time_part}</span> #{event_name_part}</p>"
    end

    html.join("\n").html_safe
  end

  def keywords_for_partner(partner)
    extra_params = {
      name: (@partner_name_filter if @partner_name_filter.present?),
      geo: (@geo_enclosure.id if @geo_enclosure.present?)
    }

    partner
      .keywords
      .order(:name)
      .map { |kw|
        link_to kw.name,
          partners_path(extra_params.merge({keyword: kw.name})),
          class: 'keyword' }
      .join(' &bull; ')
      .html_safe
  end
end

app/views/partners/index.html.haml
- content_for(:title) { "Partners" }

%h1 Partners

= form_tag partners_path, method: 'GET' do
  = text_field_tag :name, @partner_name_filter, placeholder: 'Filter by name'
  = hidden_field_tag :keyword, @keyword_for_filter.name if @keyword_for_filter.present?
  = hidden_field_tag :geo, @geo_enclosure.id if @geo_enclosure.present?
  = button_tag 'Apply', name: ''

- if @partner_name_filter.present? || @keyword_for_filter.present? || @geo_enclosure.present?
  %h2= partner_index_filter_title_text(@partner_name_filter, @keyword_for_filter, @geo_enclosure)
  %p= link_to 'Reset filter', partners_path
  %br

  - if @partners.empty?
    %h2 No results found :(

- @partners.each do |partner|
  %article.partner
    %h3= link_to partner.name, partner_path(partner.slug)
    .indent
      %p= partner.summary
      - if partner.address.ward.present?
        %p in #{link_to partner.address.ward.name, partners_path(geo: partner.address.ward.id)}
      - if partner.partner_keywords.any?
        %p= keywords_for_partner partner
      %br

app/views/partners/previous_events.html.haml
- content_for(:title) { "Previous events by #{@partner.name} - Partner" }

%h1 Previous events by #{link_to(@partner.name, partner_path(@partner.slug))}

- if @previous_event_instances.present?
  %h2 Events before #{fancy_date_format(@today)}
  .partner-event-list= render_partner_event_by_day_list(@previous_event_instances)

app/views/partners/show.html.haml
- content_for(:title) { "#{@partner.name} - Partner" }

%h1= @partner.name

- if @partner.logo_url.present?
  %img{ src: @partner.logo_url, height: '100px' }

- if @partner.address.present? || @partner.url.present?
  %p= partner_address_info(@partner)

- if @partner.contact.present?
  %p Contact #{partner_contact_info(@partner)}

- if @partner.partner_keywords.any?
  %p Keywords #{keywords_for_partner @partner}

- if @partner.summary.present?
  %p= @partner.summary

- if @partner.description.present?
  %h2 Description
  #description.indent= @partner.description_html.to_s.html_safe

- if @upcoming_events.blank? && @previous_events.blank?
  %br
  %h4 (No events found for this partner)

- else
  - if @upcoming_events.present?
    %h2 Events from #{fancy_date_format(@today)}
    .partner-event-list= render_partner_event_by_day_list(@upcoming_events)

  - if @previous_events.any?
    %br
    %br
    %h3= link_to "See #{@previous_events.count} previous events", previous_events_partner_path(@partner.slug)