config/routes.rb
Rails.application.routes.draw do
  resources :partners, only: %i[ index show ] do
    member do
      get :previous_events
    end
  end

  resources :events, only: %i[ index show ]

  get '/about' => 'home#about', as: :about

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#root"
end

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en'}
  %head
    %title= page_title_text
    %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    %link{ rel: "manifest", href: "/manifest.json" }
    %link{ rel: "icon", href: "/icon.png", type: "image/png" }
    %link{ rel: "icon", href: "/icon.svg", type: "image/svg+xml" }
    %link{ rel: "apple-touch-icon", href: "/icon.png" }
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    %head
      %nav
        %em= link_to 'EventSite', root_path
        &bull;
        = nav_link_to 'Events', events_path, controller: 'events'
        = nav_link_to 'Partners', partners_path, controller: 'partners'
        = nav_link_to 'About', about_path, controller: 'home', action: 'about'
      %hr

    = yield

    %br
    %br

    %footer
      %p
        %small Copyright &copy; 2024, MeCorp. Data provided by <a href="https://placecal.org/"><em>PlaceCal</em></a>